### ISSUE TITLE
Is the library still under maintenance?

### ISSUE THREAD

**Issue by ajiho** [dfcreative/draggy#6]
As shown in the title

**Comment by dy** [comment]
Kind of. I wouldn't recommend using it, but it is kept alive for the meantime.

**Comment by ajiho** [comment]
Thank you for your work. Is there a better alternative that you can recommend?

**Comment by dy** [comment]
Depends on your use-case, if it's simple dragging I'd compare:
* [interactjs](https://www.npmjs.com/package/interactjs)
* [shipify/draggable](https://www.npmjs.com/package/@shopify/draggable)
* [draggabilly](https://www.npmjs.com/package/draggabilly)

**Comment by ajiho** [comment]
Thank you, I got  [draggabilly](https://www.npmjs.com/package/draggabilly)
